server:
  port: 8089
spring:
  application:
    name: demo-consumer
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:9999/eureka
demo-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    #ConnectTimeout: 250 # 连接超时时间(ms)
    #ReadTimeout: 1000 # 读取数据超时时间(ms)

#我们可以通过`hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds`来设置Hystrix全局的超时时间。
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2000 # 设置hystrix的超时时间为2秒
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能